# Generated by Django 3.1 on 2020-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_business_owner', models.BooleanField()),
                ('is_customer', models.BooleanField()),
                ('email', models.EmailField(help_text='아이디로 사용할 이메일 계정', max_length=255, unique=True, verbose_name='이메일 아이디')),
                ('name', models.CharField(help_text='이름', max_length=255, verbose_name='이름')),
                ('birthday', models.DateField(help_text='생일', verbose_name='생일')),
                ('phone_number', models.CharField(help_text='휴대폰 전화번호 입력(-제외)', max_length=11, verbose_name='전화번호')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '베이스 사용자',
                'verbose_name_plural': '베이스 사용자',
                'ordering': ('-date_joined',),
            },
        ),
    ]
