# Generated by Django 3.1 on 2020-08-14 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_businessowner_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessowner',
            options={'verbose_name': '사업주', 'verbose_name_plural': '사업주'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '소비자', 'verbose_name_plural': '소비자'},
        ),
    ]
