# Generated by Django 3.1 on 2020-08-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='store',
        ),
        migrations.AddField(
            model_name='customer',
            name='store',
            field=models.ManyToManyField(null=True, to='users.Store'),
        ),
    ]
