# Generated by Django 3.1 on 2020-08-26 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200826_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='store',
        ),
        migrations.AddField(
            model_name='prepayment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
    ]
