# Generated by Django 3.1 on 2020-08-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200826_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('prepayment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.prepayment')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.store')),
            ],
        ),
    ]
